### ISSUE TITLE
麻烦问一下，这个项目怎么用

### ISSUE THREAD

**Issue by Yao-DY** [GuiLingWN/tinify-node#1]
是直接运行.bat文件么，运行完没有任何反应啊，更新了config.json文件里的key也没反应（换成了自己的一个API Key）。
或者是要运行.js文件？请问需要什么环境？

**Comment by GuiLingWN** [comment]
先npm i 安装环境，然后运行 index.js

**Comment by Yao-DY** [comment]
> 先npm i 安装环境，然后运行 index.js

十分感谢
